// =============================================================
// aiService.js – Real Google Gemini LLM Integration for Synapse AI
// =============================================================

// Active supported Gemini models in order of performance & availability
const GEMINI_MODELS = [
  'gemini-3.6-flash',
  'gemini-3.5-flash',
  'gemini-3.1-flash-lite',
  'gemini-flash-latest',
  'gemini-3.7-flash',
];

/**
 * Get the configured Gemini API key from environment variables.
 */
export function getGeminiApiKey() {
  try {
    if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_GEMINI_API_KEY) {
      return import.meta.env.VITE_GEMINI_API_KEY;
    }
  } catch {
    // Ignore ReferenceError in non-Vite environments
  }

  try {
    if (typeof process !== 'undefined' && process.env?.VITE_GEMINI_API_KEY) {
      return process.env.VITE_GEMINI_API_KEY;
    }
  } catch {
    // Ignore ReferenceError in environments where process is undefined
  }

  return '';
}

/**
 * Builds system instruction for the Synapse AI Tutor persona.
 */
function buildSystemInstruction(contextData = {}) {
  const { user, modeLabel, tasks = [], notes = [], events = [] } = contextData;

  const openTasks = tasks.filter((t) => t.status !== 'done');
  const highPriority = openTasks.filter((t) => t.priority === 'high');
  const studentName = user?.name || 'Student';
  const course = user?.course || user?.major || 'General Studies';

  const workspaceSummary = `
Student Profile:
- Name: ${studentName}
- Course/Major: ${course}
- Current Academic Mode: ${modeLabel || 'Normal Semester'}
- Open Tasks (${openTasks.length}): ${openTasks.slice(0, 5).map((t) => `${t.title} [${t.priority}]`).join(', ') || 'None'}
- High Priority Tasks: ${highPriority.map((t) => t.title).join(', ') || 'None'}
- Total Notes Saved: ${notes.length}
- Upcoming Events: ${events.slice(0, 3).map((e) => `${e.title} (${e.date})`).join(', ') || 'None'}
`;

  return {
    parts: [
      {
        text: `You are "Synapse AI Tutor", a real, intelligent, and highly conversational university academic tutor inside the Synapse Adaptive Learning Workspace.

CONVERSATIONAL INSTRUCTIONS:
- You are a real conversational AI assistant (behave like ChatGPT).
- Communicate naturally, warmly, and interactively.
- For simple greetings ("Hi", "Hello", "Hiii"), respond in 1-2 friendly sentences (e.g. "Hello Thara! How can I help you with your studies today?").
- DO NOT use repetitive canned intros like "Great question!", "Here is a structured breakdown", "Core Concept", "Active Engagement", or "Consistent Execution" unless requested by the user.
- When asked academic or study questions, give clear, direct, and well-reasoned explanations.
- Maintain conversation context across multi-turn messages (e.g., if the user asks "Give an example", provide an example for the topic previously discussed).
- Tailor guidance using the student's live workspace context when relevant.

LIVE WORKSPACE CONTEXT:
${workspaceSummary}`
      }
    ]
  };
}

/**
 * Converts chat message history into the Gemini API `contents` format.
 * Ensures the conversation starts with a 'user' role and strictly alternates.
 */
function formatMessagesForGemini(messages) {
  const validMsgs = [];
  let startedUser = false;

  for (const msg of messages) {
    if (!msg.text || !msg.text.trim()) continue;
    if (msg.role === 'user') {
      startedUser = true;
    }
    if (startedUser) {
      validMsgs.push(msg);
    }
  }

  const formatted = [];
  for (const msg of validMsgs) {
    const role = msg.role === 'user' ? 'user' : 'model';
    if (formatted.length > 0 && formatted[formatted.length - 1].role === role) {
      formatted[formatted.length - 1].parts[0].text += `\n\n${msg.text}`;
    } else {
      formatted.push({
        role,
        parts: [{ text: msg.text }],
      });
    }
  }

  return formatted;
}

/**
 * Send chat message history to Google Gemini API and return the real AI response.
 *
 * @param {Array} messages - Array of { role: 'user'|'ai', text: string }
 * @param {Object} contextData - Live workspace context (user, tasks, notes, events, modeLabel)
 * @returns {Promise<string>} The AI response string generated by Gemini LLM
 */
export async function sendChatMessageToGemini(messages, contextData = {}) {
  const apiKey = getGeminiApiKey();

  if (!apiKey || apiKey.trim() === '' || apiKey === 'YOUR_GEMINI_API_KEY_HERE') {
    console.error('Gemini API Error: Missing or invalid VITE_GEMINI_API_KEY.');
    return 'AI Tutor is temporarily unavailable. Please try again shortly.';
  }

  const systemInstruction = buildSystemInstruction(contextData);
  const contents = formatMessagesForGemini(messages);

  if (contents.length === 0) {
    return 'AI Tutor is temporarily unavailable. Please try again shortly.';
  }

  const payload = {
    systemInstruction,
    contents,
    generationConfig: {
      temperature: 0.7,
      topP: 0.95,
      maxOutputTokens: 1024,
    },
  };

  // Attempt models in fallback order
  for (const modelName of GEMINI_MODELS) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s timeout

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`Gemini API Error (${modelName} HTTP ${response.status}):`, errorText);
        continue; // Try next model in sequence
      }

      const responseText = await response.text();
      let data;
      try {
        data = JSON.parse(responseText);
      } catch (parseErr) {
        console.error(`Gemini API Parse Error (${modelName}):`, parseErr);
        continue;
      }

      const candidateText = data.candidates?.[0]?.content?.parts
        ?.map((part) => part.text || '')
        .join('');

      if (candidateText && candidateText.trim()) {
        return candidateText.trim();
      }
    } catch (err) {
      console.error(`Gemini API Call Exception (${modelName}):`, err.message || err);
    }
  }

  // User-friendly error message if all API attempts fail
  return 'AI Tutor is temporarily unavailable. Please try again shortly.';
}
